name: 'Swift Coverage Report'
description: 'Report SPM test coverage summary and lcov file'
author: 'Maxime Epain'
branding:
    icon: 'check-circle'
    color: 'orange'
inputs:
    output-file:
        description: 'The output file path'
        required: false
        default: '.build/debug/codecov/lcov.info'
    file-format:
        description: 'The output file format'
        required: false
        default: 'lcov'
    instr-profile:
        description: 'The input instrumentation profile file'
        required: false
        default: '.build/debug/codecov/default.profdata'
    is-spm:
        description: 'Is the current porject an SPM project?'
        type: boolean
        required: false
        default: true
    test-binary:
        description: 'The test binary'
        required: false
runs:
    using: 'node16'
    main: 'index.js'
